[workspace]
members = [
    "crates/ast",
    "crates/checker",
    "crates/cli",
    "crates/common",
    "crates/expander",
    "crates/ir",
    "crates/macros",
    "crates/parser",
    "crates/server",
    "crates/symbols",
    "crates/transpiler",
    "crates/types",
    "crates/enum_from_derive",
]
resolver = "2"
