[package]
name = "tine_cli"
version.workspace = true
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4", features = ["derive"] }

tine_common = { path = "../common" }
tine_parser = { path = "../parser" }
tine_checker = { path = "../checker" }
tine_transpiler = { path = "../transpiler" }
notify = "8.2.0"
notify-debouncer-mini = "0.7.0"
